### ISSUE TITLE
Address type is not exported anymore in stable release

### ISSUE THREAD

**Issue by danlutz** [commercetools/commercetools-typescript-sdks#25]
Hi!

Love the `@commercetools/typescript-sdk` package, helps alot with typesafe code!

We noticed that after upgrading to the stable release, the "Address" interface/type is not exported anymore.

Importing it like:
```ts
import { Address } from "@commercetools/typescript-sdk"
```

has previously worked, not now anymore.

It is still in the `cart.d.ts` file though

**Comment by MicheleRezk** [comment]
Thanks for reporting the issue, you're right Address model has moved to common.d.ts but your import should have worked, we already solved the issue at https://github.com/commercetools/commercetools-typescript-sdks/commit/9caae709409fdd34505da52079e82dbfcfde7f83 and you can update to typescript to version 1.1.0 and it will be fine.

**Comment by danlutz** [comment]
Thanks a lot, it's working now!
